name: Playwright Tests
on:
  workflow_run:
    workflows: ["CI"] # The name of the main workflow you want to trigger from
    types:
      - completed # Trigger when the workflow is completed
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Playwright package
        run: pnpm add -D playwright
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: actions/checkout@v4
        uses: actions/checkout@v4
      - name: Install project dependencies
        run: pnpm install
      - name: Run E2E Playwright tests
        run: pnpm test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
